create table settings_profile (
    id bigint generated by default as identity primary key,
    goal_amount numeric(19, 2) not null,
    current_corpus numeric(19, 2) not null,
    total_invested_capital numeric(19, 2) not null,
    default_monthly_amount numeric(19, 2) not null,
    annual_step_up_percentage numeric(5, 2) not null,
    salary_day integer not null,
    risk_preference varchar(32) not null,
    time_zone varchar(64) not null,
    telegram_chat_id varchar(64),
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create table monthly_cycle (
    id bigint generated by default as identity primary key,
    cycle_month varchar(7) not null unique,
    salary_date date not null,
    expected_amount numeric(19, 2) not null,
    available_amount numeric(19, 2) not null,
    actual_invested_amount numeric(19, 2),
    invested_on date,
    status varchar(32) not null,
    notes varchar(500),
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);
